### ISSUE TITLE
host and replicaset ignored

### ISSUE THREAD

**Issue by dicolasi** [Apicurio/apicurio-registry-operator#107]
I have the following deployment: 

```
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: schema-registry
  labels:
    app: apicuro-schema-registry
configuration:
  persistence: "kafka"
  kafka:
    bootstrapServers: kafka-prod-kafka-bootstrap.kafka.svc:9092
deployment:
  host: registry.data.property.xyz
  replicas: 3
```

however, both host and replicas are completely ignored. Am I missing something?
