### ISSUE TITLE
Allow/document setup of sql database via Secret

### ISSUE THREAD

**Issue by pilhuhn** [Apicurio/apicurio-registry-operator#142]
I have a Postgres DB set up and have the name+cedentials in a secret.
The operator should allow to configure a registry from that secret.

Basically allow to set the properties in a "valueFrom: secretKeyRef" way.

As an example for what I mean: For a (different) quarkus project that uses JPA, I am setting the DC like this:

```
    spec:
      containers:
      - image: quay.io/pilhuhn/log-funq:jvm
        name: log-funq
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: postgresql
          - name: DB_PORT
            value: "5432"
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: QUARKUS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name

```

**Comment by EricWittmann** [comment]
I think this is already on the roadmap for the operator (not sure if it's tracked in another GH issue or not), but @jsenko would know better.

**Comment by jsenko** [comment]
Than you. Yes, it's a feature we plan to add in a next release. It's referenced here #20 , but it's good to have it as a separate issue.

**Comment by dweber019** [comment]
Had the same issue with sealed secrets ;) looking forward for the fix in the next release.

**Comment by from-nibly** [comment]
Any news on this, is there a workaround? I can't commit secrets into my git repo, the only way I can pass secrets around is a sealed secret.

**Comment by dweber019** [comment]
I saw you already implemented the feature
https://github.com/Apicurio/apicurio-registry-operator/blob/main/api/v1/apicurioregistry_types.go#L39

When will 1.1.x be released?

**Comment by uladzislau-orlovskiy** [comment]
> I saw you already implemented the feature https://github.com/Apicurio/apicurio-registry-operator/blob/main/api/v1/apicurioregistry_types.go#L39
> 
> When will 1.1.x be released?

its not implemented
look at line 69

https://github.com/Apicurio/apicurio-registry-operator/blob/main/api/v1/apicurioregistry_types.go#L69

**Comment by uladzislau-orlovskiy** [comment]
@jsenko any workaround avalible? can I just mount secretfiles and tossthem via env variables to docker image?

**Comment by jsenko** [comment]
hi, at the moment the suggested approach is to use environment variables, as you said, via `spec.configuration.env` field.

**Comment by jsenko** [comment]
> When will 1.1.x be released?
Version `1.1.0-v2.4.12.final` has been release some time ago. I plan to update the operand to `2.5.x`.

**Comment by uladzislau-orlovskiy** [comment]
> hi, at the moment the suggested approach is to use environment variables, as you said, via `spec.configuration.env` field.

Yup but there is no DB_PASSWORD_FILE env variable like in keycloack. And pod that handles CRD ApicurioRegistry resource don't handle secretref. Any plans for apicurio to handle db credentials via files like keycloack for example do?:) @jsenko

**Comment by jsenko** [comment]
Are you sure this does not work?
```
spec:
  configuration:
    env:
      - name: REGISTRY_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
```
