### ISSUE TITLE
The service created by the operator is missing the "port name"

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry-operator#149]
Reported by Abel Bouchama:

![image](https://user-images.githubusercontent.com/1890703/145447412-37666818-7a52-404e-858f-4c4a7e569719.png)

```
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
```
