### ISSUE TITLE
How can i add labels to the pod?

### ISSUE THREAD

**Issue by wangshu3000** [Apicurio/apicurio-registry-operator#150]
I'm using this apicurio-registry-operator to deploy the registry on kubernetes.
I have deployed the operator, the operator pod is up and running.
We have an compliance rule that each pods need to be taged a label to indicate the projectid.
The registry pod is managed by the operator. 
Could anyone tell me how can i add the label to the generated pod?
`apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry-mem
  labels:
    projectid: 112233
spec:
  configuration:
    persistence: "mem"`
I tried to add the label to ApicurioRegistry, but it'll not pass this label to the generated pod.

Thanks.

**Comment by ajborley** [comment]
We would also like to be able to specify pod labels in the ApicurioRegistry custom resource, and as far as I can see there is no way to do that currently. 

I'd like to propose a CRD change to add in the ability to provide additional pod labels. I suggest the natural place would be to add a `metadata` object to the `spec.deployment` object. The new `metadata` object would contain a `labels` object to contain the desired additional labels, which would get added to the `spec.template.metadata.labels` object in the deployment created by the operator. For example:

```
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: my-registry
spec:
  deployment:
    # ...
    metadata:
      labels:
        mylabel: myvalue
```

Hopefully that makes sense. @jsenko @famartinrh @EricWittmann WDYT?

I'm happy to work on this change, if it's agreed as a reasonable approach. Thanks!
