### ISSUE TITLE
Specifiy Apicurio Registry Image (or version)

### ISSUE THREAD

**Issue by redsk** [Apicurio/apicurio-registry-operator#176]
Is there a way to do this? I need to upgrade the Apicurio Registry to a version >= `2.1.4.Final` due to [this issue](https://www.apicur.io/blog/2021/12/09/kafkasql-storage-and-security)

**Comment by jsenko** [comment]
hi, you can try to specify an image using `spec.deployment.image` property in the ApicurioRegistry CR.
As to the second question, Operator itself does not currently support that, but you can open a new issue or contribute. This could possibly be a more general feature to tell it to modify the Deployemetn in some generic way. The only way to do that at the moment that I can think of is to modify the pod template in the Deployment after the Operator created it and add `initialDelaySeconds`.

**Comment by Pablo-platypus** [comment]
same issue here, maybe we can build and deploy the operator manually instead of using operatorhub.io? We can edit the version to be used under the install/.yaml? Any advice or pointers on this?

**Comment by marcosschroh** [comment]
Sorry, but the documentation is absolutely terrible. It would be so nice when someone decides to open source a project that documentation is a key point. To override the image you should do:

```yaml

apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: des-apicurioregistry-mem
spec:
  configuration:
    persistence: "mem" # Optional (default value)
    # NOTE: No additional configuration required for *dev* deployment

    # ui:
    #   readOnly: true

    env:
      - name: AUTH_ENABLED
        value: "true"
      - name: AUTHZ_ENABLED
        value: "true"
      ...
  
  deployment:
    image: quay.io/apicurio/apicurio-registry-mem:2.5.11.Final
    ...
```
