### ISSUE TITLE
OLM Subscription does not honor Subscription Configs / Allow disabling v1 APIs

### ISSUE THREAD

**Issue by dlydiard** [Apicurio/apicurio-registry-operator#196]
To workaround an issue with ApiCurio v1 APIs circumventing auth, I attempted to add the suggested [environment variable](https://github.com/Apicurio/apicurio-registry/issues/2394) to the OLM Subscription to disable v1 APIs. However, the Subscription does not append environment variables to the `ApicurioRegistry` `Deployment`. According to the OLM specs, Subscription Configs should be supported to make adjustments to the installation. https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#resources

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apicurio-registry-operator
  namespace: apicurio-registry-operator
spec:
  channel: 2.x
  name: apicurio-registry
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  config:
    env:
      - name: REGISTRY_DISABLE_APIS # this doesn't work...
        value: /apis/ibmcompat/.*,/api/.* # v1 APIs circumvent auth, force users to use v2 of the api
```

Also would be nice to support disabling v1 APIs directly via the `ApicurioRegistry` CRD, since this is a security hole.
