### ISSUE TITLE
Metrics not accessible with disableHttp=true

### ISSUE THREAD

**Issue by pantaoran** [Apicurio/apicurio-registry-operator#247]
In my custom resource `ApicurioRegistry` I want to set
```
    spec:
      configuration:
        security:
          https:
            disableHttp: true
```
for security hygiene. My enterprise environment forbids plain http.
When I set that, port 8080 is no longer exposed on the registry pod. But then, my `ServiceMonitor` still guides Prometheus to port 8080 for metrics, which seems to fail since I don't see those metrics in Prometheus afterwards. Only when I set `disableHttp` back to `false` can I see metrics again.

What's the idea here? Is this a bug?
How can I disable the plain endpoint for API clients, but still get metrics to operate the registry?
