### ISSUE TITLE
Https doesn't work with the latest version of Apicurio Registry.

### ISSUE THREAD

**Issue by avi5kdonrh** [Apicurio/apicurio-registry-operator#254]
The following deployment doesn't enable the https port and logs these warnings at the start:
  ```
apiVersion: registry.apicur.io/v1
  kind: ApicurioRegistry
  metadata:
    name: reg
  spec:
    deployment:
     image: registry.redhat.io/apicurio/apicurio-registry-kafkasql-rhel8:2.6.1
    configuration:
      security:
        https:
          secretName: mytls-secret
      persistence: kafkasql
      kafkasql:
        bootstrapServers: "my-cluster-kafka-bootstrap:9092"
```
2024-08-12 18:37:26 WARN <> [null] (main) Unrecognized configuration key "quarkus.http.ssl.certificate.key-file" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-12 18:37:26 WARN <> [null] (main) Unrecognized configuration key "quarkus.http.ssl.certificate.file" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

....

It only listens on the http port:

2024-08-12 18:37:36 INFO <_> [io.quarkus.bootstrap.runner.Timing] (main) apicurio-registry-storage-kafkasql 2.6.1.redhat-00003 on JVM (powered by Quarkus 3.8.4.redhat-00002) started in 11.219s. Listening on: http://0.0.0.0:8080

Apparently the http ssl config key names were changed in the more recent Quarkus version.

https://quarkus.io/guides/http-reference#configuring-the-http-server-directly
