### ISSUE TITLE
adding istio sidecar to apicurio instance

### ISSUE THREAD

**Issue by L040639** [Apicurio/apicurio-registry-operator#259]
@jsenko      @EricWittmann  

I am trying to add a istio sidecar to the apicurio instance in my redhat openshift cluster but it was not added. Looked into CRD and not finding a way to add the sidecar annotation. Apicurio has this option ??

```yaml
kind: ApicurioRegistry
apiVersion: registry.apicur.io/v1
metadata:
  name: schema-platform-mesh
  namespace: schema-registry-services
spec:
  configuration:
    persistence: 'sql'
    sql:
      dataSource:
        url: 'jdbc:postgresql://<XXXXXX>-2.rds.amazonaws.com:5432/'
        userName: '<XXXX>'
        password: ${POSTGRES_PASSWORD}
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: password
      - name: QUARKUS_LOG_LEVEL
        value: 'debug'
        podTemplateSpecPreview:
  deployment:
    podTemplateSpecPreview:
        metadata:
             annotations:
                    sidecar.istio.io/inject: "true"
```

**Comment by jsenko** [comment]
hi, try this:

```
kind: ApicurioRegistry
apiVersion: registry.apicur.io/v1
metadata:
  name: schema-platform-mesh
  namespace: schema-registry-services
spec:
  configuration:
    persistence: 'sql'
    sql:
      dataSource:
        url: 'jdbc:postgresql://<XXXXXX>-2.rds.amazonaws.com:5432/'
        userName: '<XXXX>'
        password: ${POSTGRES_PASSWORD}
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: password
      - name: QUARKUS_LOG_LEVEL
        value: 'debug'
        podTemplateSpecPreview:
  deployment:    
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
```

The PTS was added later than `spec.deployment.metadata`. See also https://www.apicur.io/registry/docs/apicurio-registry-operator/1.2.0-dev-v2.6.x/assembly-operator-configuration.html#spec .
