### ISSUE TITLE
Wide ClusterRole

### ISSUE THREAD

**Issue by mdecalf** [Apicurio/apicurio-registry-operator#263]
I am looking to deploy the operator. Having reviewed the [install.yml](https://github.com/Apicurio/apicurio-registry-operator/blob/main/install/install.yaml), I am quite surprised by the scope of the ClusterRole, especially:

```
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  - services/finalizers
  verbs:
  - '*'
```

Why are these cluster-wide permissions used?
