### ISSUE TITLE
Default route is not valid and does not work

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry-operator#30]
Tested on Openshift 4.4.
Using version 0.0.2 of the operator and this example CR will make operator create the default route

```
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: apicurio-registry-infinispan
spec:
  configuration:
    persistence: infinispan
    infinispan:
      clusterName: registry-application
```

The created route is like 
``` 
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurio-registry-infinispan
spec:
    host: apicurio-registry-infinispan.registry-infinispan-namespace
    path: /
    to:
      kind: Service
      name: apicurio-registry-streams-service-ktqwr
      weight: 100
```

that hostname is not resolvable because it does not end with the cluster dns domain
