### ISSUE TITLE
Route auto-generation may pick up a wrong value

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry-operator#42]
... if there are multiple `routerCanonicalHostname` values, e.g.
```
status:
  ingress:
    - host: >-
        example-apicurioregistry.service-registry-test.apps.***.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2020-06-25T14:26:21Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps.***.com
    - host: >-
        example-apicurioregistry.service-registry-test.apps.***.com
      routerName: sharded
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2020-06-25T14:26:20Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps-sharded.basedomain.example.net
```
