### ISSUE TITLE
Make it easier to support SSL

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry-operator#70]
Quarkus has built-in support for configuring SSL.  Documentation for that can be found here:

https://quarkus.io/guides/http-reference#supporting-secure-connections-with-ssl

It would be nice if the operator made enabling this feature easier/more convenient for users.

**Comment by ajborley** [comment]
I have the beginnings of a fix to enable internal TLS for accessing the Apicurio Registry when deployed by the operator. My proposal is to add a `tls` field to the `spec.deployment` section where a secret can be specified that contains the certificate and key. 

For example:
```
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: example-service-registry
spec:
  ...
  deployment:
    tls:
      secretName: my-secret
      certificate: my-tls-certificate.crt
      key: my-tls-key.key
```

The operator would then update the deployment to mount the certificate and key from the Secret and provide them as Quarkus properties in the pod env vars, meaning that the registry server starts up with SSL enabled for internal (pod-to-pod) communication. Providing the TLS Secret would also disable the HTTP port, so only secured communications would be allowed.

e.g. the extra Quarkus properties become:
```
quarkus.http.ssl.certificate.file=/path/to/my-secret/my-tls-certificate.crt
quarkus.http.ssl.certificate.key-file=/path/to/my-secret/my-tls-key.key
quarkus.http.insecure-requests=disabled
```

This can then be linked with the proposal in #90 which would allow the Ingress to be specified, and mean secured external communications all the way through to the registry would be possible via a `termination: passthrough` configuration on the Ingress/Route.

@jsenko @carlesarnal Hope this all makes sense! WDYT?
