### ISSUE TITLE
Registry does not start with 100m CPU "limits", so IMO it should not be default "requests"

### ISSUE THREAD

**Issue by jhutar** [Apicurio/apicurio-registry-operator#81]
After an hour, it was still not started. When changed to to `200m` CPU limits&requests, it started. Mine OCP nodes were `m5.2xlarge`.

**Comment by famartinrh** [comment]
This are the default values
```
        resources:
          limits:
            cpu: "1"
            memory: 1300Mi
          requests:
            cpu: 100m
            memory: 600Mi
```

I've never had issues with registry resources requests/limits

Have you verified the events in your cluster?
Try something like this first `kubectl describe deployment <your-deployment-name>`

**Comment by jhutar** [comment]
Yeah, this would be a corner case, but starting with both requests & limits set to 100m causes the registry does not start. This simulates overloaded cluster where user have 100m CPU free, but nothing more (so pod is created, but does not get a single processor tick more than 100m).

I agree it is a theoretical possibility, but IMHO it is still a bug. Lower boundary should ensure that when resource is set to it, service starts.

If you disagree, please feel free to close this.

**Comment by famartinrh** [comment]
oh, sorry, my bad, now I get your point. I wasn't verifiying this properly ...

I've been playing with requests&limits + readines and livenes probes and I ended up with this minimum configuration

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
```

So this will be 
readiness and liveness probes will have initial delay of 15s
minimum resources will be 500m cpu and 512Mi of memory
maximuim resources will continue the same 1 cpu and 1300Mi

is this ok for everyone @Apicurio/developers  ?
